spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 8.x? JDBC ????
    url: jdbc:mysql://localhost:3306/chatdb?useSSL=false&serverTimezone=Asia/Seoul  # DB ?? URL (?? MySQL, chatdb ??, SSL ???, ??? ??)
    username: root       # MySQL ??? ??
    password: 1234       # MySQL ????

  jpa:
    database: mysql      # ?? ?????? ?? (???? ?? ? ?? ?)
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Hibernate? ??? SQL ??
    generate-ddl: true   # DDL (??? ?? ?) ?? ?? ?? (?? ddl-auto? ?? ??)
    hibernate:
      ddl-auto: update   # ??? ?? ?? ?? (create, update, validate, none ?)
    show-sql: true       # ???? SQL? ??? ?? (????)

server:
  port: 8081             # ??? ?? ?? ??? ??? ?? (??? 8080)
